CREATE TABLE SELECT_TEST(
	ID NUMBER,
	NAME VARCHAR(100),
	CREATED_DATE TIMESTAMP
);


INSERT INTO SELECT_TEST VALUES
(1, 'sadvasdvsad', CURRENT_TIMESTAMP),
(2, 'sdfbsdfb', CURRENT_TIMESTAMP),
(3, 'dfsbsdfb', CURRENT_TIMESTAMP),
(4, 'sdfbdsfb', CURRENT_TIMESTAMP),
(5, 'sdfbsdfb', CURRENT_TIMESTAMP),
(6, 'sdfbsdfb', CURRENT_TIMESTAMP)
;


select * from SELECT_TEST;





CREATE TABLE SAMPLE_DESCRIPTION(
	ID VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(1000),
	OUTPUT_MAPPING VARCHAR(1000),
	QUERY VARCHAR(1000),
	CREATED_DATE TIMESTAMP
);


select * from SAMPLE_DESCRIPTION;

INSERT INTO SAMPLE_DESCRIPTION(ID, NAME, OUTPUT_MAPPING, QUERY, CREATED_DATE) VALUES
(
'd097b1a6-04da-496f-9a37-fb61f83f23fc', 
'test',
'{"NAME":"name"}',
'SELECT NAME FROM SELECT_TEST',
CURRENT_TIMESTAMP
)
;