@host=http://localhost:8080

# Получение всех данных
GET {{host}}/api/dyn-s?selName=select-customer

###

# Получение данных с фильтрацией
GET {{host}}/api/dyn-s?selName=search-customer&selMap=firstName,city&selFil=Pao

###

# Получение данных группового запроса
GET {{host}}/api/dyn-s?selName=sum-of-customer&selMap=firstName,total